### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by noellesugar99** [maximedrn/pinterest-automatic-upload#7]
Login to Pinterest. Logged.

Traceback (most recent call last):
  File "/Users/noelle/Downloads/pinterest-automatic-upload-master/main.py", line 306, in <module>
    data.format_data(pin)  # Get data's pin.
  File "/Users/noelle/Downloads/pinterest-automatic-upload-master/main.py", line 98, in format_data
    eval(f'self{self.filetype}_file()')
  File "<string>", line 1, in <module>
  File "/Users/noelle/Downloads/pinterest-automatic-upload-master/main.py", line 111, in csv_file
    self.create_data([data.strip() for data in pin_data])
  File "/Users/noelle/Downloads/pinterest-automatic-upload-master/main.py", line 56, in create_data
    self.file_path = os.path.abspath(str(data[1]))  # Required.
IndexError: list index out of range
(base) noelle@noellenoMacBook-Air pinterest-automatic-upload-master % 

hi do you know what i should do?

**Comment by noellesugar99** [comment]
hi i might have solved that but now

Login to Pinterest. Logged.

Traceback (most recent call last):
  File "/Users/noelle/Downloads/pinterest-automatic-upload-master/main.py", line 68, in create_data
    date = datetime.strptime(data[6], '%Y-%m-%d')
  File "/Users/noelle/opt/anaconda3/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Users/noelle/opt/anaconda3/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/noelle/Downloads/pinterest-automatic-upload-master/main.py", line 318, in <module>
    data.format_data(pin)  # Get data's pin.
  File "/Users/noelle/Downloads/pinterest-automatic-upload-master/main.py", line 110, in format_data
    eval(f'self{self.filetype}_file()')
  File "<string>", line 1, in <module>
  File "/Users/noelle/Downloads/pinterest-automatic-upload-master/main.py", line 118, in json_file
    self.create_data([pin_data[data].strip() for data in pin_data])
  File "/Users/noelle/Downloads/pinterest-automatic-upload-master/main.py", line 73, in create_data
    raise Exception("Date format is invalid")
Exception: Date format is invalid
(base) noelle@noellenoMacBook-Air pinterest-automatic-upload-master % 


plz help><

**Comment by noellesugar99** [comment]
the date im using is either blank or
       "date": "25/12/2021 12:00"
both dont work...

**Comment by maximedrn** [comment]
Can you send me the file used?
You may forgot something else
